import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';

async function readText(path) {
  return readFile(new URL(`../../${path}`, import.meta.url), 'utf8');
}

test('shared site script applies the compiled-inventory publication boundary', async () => {
  const script = await readText('assets/main.js');
  for (const fragment of [
    'FAIL_CLOSED_FORMAL_STATUS',
    'function isConservativeFormalStatus(status, inventory)',
    'function validateInventory(inventory)',
    'function validateConcreteGate(status, inventory)',
    'function validateMilestones(status)',
    'function validateStatus(status, inventory)',
    'PNP-FORMAL-RECONSTRUCTION-STATUS-2026-07-23-72',
    'PNP-LEAN-THEOREM-INVENTORY-2026-07-23-72',
    '02229cdf19b7d630a68733a80a4bad00f7d9c7ae3bfd64f42095e5b2c5e4f474',
    'declarations: 10493',
    'theorems: 5841',
    'assumptionFreeTheorems: 3333',
    'excludedPrivateDeclarations: 3971',
    'modules: 92',
    'axioms: 4',
    'PNP.Concrete.FinalUniversalDesign.cnfSATInNP',
    'PNP.Concrete.CookLevin.VerifierTableauProblem.encodedFormula_mem_CNFSAT_iff_language',
    'PNP.Concrete.CookLevin.VerifierTableauProblem.formulaBitSchedule_length',
    'PNP.Concrete.CookLevin.VerifierTableauProblem.formulaBitSchedule_emit_eq_encodedFormula',
    'PNP.Concrete.CookLevin.BuilderInputPrefix.workRunExact',
    'PNP.Concrete.CookLevin.BuilderInputPrefix.malformedTallyScanSymbol_timeout',
    'status.leanConcreteCookLevinBuilderInputPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderInputPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderInputPrefixLiteralFramerLaunchFormalized === true',
    'PNP.Concrete.CookLevin.BuilderTokenAppender.appendToken_workRunExact',
    'PNP.Concrete.CookLevin.BuilderTokenAppender.firstHeaderToken_bits_eq_encodedFormula_take_two',
    'status.leanConcreteCookLevinBuilderTokenAppenderFormalized === true',
    'status.leanConcreteCookLevinBuilderTokenAppenderAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderTokenAppenderFirstFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderTokenAppenderInputPrefixComposed === true',
    'status.leanConcreteCookLevinBuilderFirstTokenPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstTokenPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFirstTokenPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderUnaryPolynomialFormalized === true',
    'status.leanConcreteCookLevinBuilderUnaryPolynomialAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderCompleteHeaderFormalized === true',
    'status.leanConcreteCookLevinBuilderCompleteHeaderAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderCompleteHeaderExactFormulaBitsFormalized === true',
    'PNP.Concrete.CookLevin.BuilderBodyStartPrefix.bodyStartTokens_eq_canonical_prefix',
    'PNP.Concrete.CookLevin.BuilderBodyStartPrefix.nextTokenSlot_eq_formulaVariableSlotBound_add_two',
    'status.leanConcreteCookLevinBuilderBodyStartPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderBodyStartPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderBodyStartPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderBodyStartPrefixRetainedNextTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFirstLiteralPrefix.firstLiteralTokens_eq_canonical_formula_prefix',
    'PNP.Concrete.CookLevin.BuilderFirstLiteralPrefix.finalTokenBits_eq_encodedFormula_firstLiteral',
    'status.leanConcreteCookLevinBuilderFirstLiteralPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstLiteralPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFirstLiteralPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstLiteralPrefixRetainedNextTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFirstClausePrefix.firstClauseTokens_eq_canonical_formula_prefix',
    'PNP.Concrete.CookLevin.BuilderFirstClausePrefix.finalTokenBits_eq_encodedFormula_firstClause',
    'status.leanConcreteCookLevinBuilderFirstClausePrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstClausePrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFirstClausePrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstClausePrefixRetainedNextTokenCoordinateFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstClausePrefixCompleteFirstClauseFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFirstClausePaddingRun.specification_padding_run',
    'PNP.Concrete.CookLevin.BuilderFirstClausePaddingRun.secondClauseStart_direct_eq_sep',
    'status.leanConcreteCookLevinBuilderFirstClausePaddingRunFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstClausePaddingRunAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFirstClausePaddingRunRemainingPaddingCountFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstClausePaddingRunSecondClauseStartFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstClausePaddingRunNoEmissionSpecificationFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondClauseSeparatorStep.specification_separator_step',
    'PNP.Concrete.CookLevin.BuilderSecondClauseSeparatorStep.nextTokenSlot_direct_eq_f',
    'status.leanConcreteCookLevinBuilderSecondClauseSeparatorStepFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSeparatorStepAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSeparatorStepExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSeparatorStepSecondClauseSeparatorFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSeparatorStepRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondClauseFirstLiteralPrefix.specification_firstLiteral_sign_step',
    'PNP.Concrete.CookLevin.BuilderSecondClauseFirstLiteralPrefix.specification_firstLiteral_terminator_step',
    'PNP.Concrete.CookLevin.BuilderSecondClauseFirstLiteralPrefix.finalTokenBits_eq_encodedFormula_secondClauseFirstLiteral',
    'PNP.Concrete.CookLevin.BuilderSecondClauseFirstLiteralPrefix.finalTokenSlot_eq_secondClauseStart_add_three',
    'status.leanConcreteCookLevinBuilderSecondClauseFirstLiteralPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseFirstLiteralPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondClauseFirstLiteralPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseFirstLiteralPrefixCompleteFirstNegativeLiteralFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseFirstLiteralPrefixRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondClauseSecondLiteralPrefix.specification_secondLiteral_sign_step',
    'PNP.Concrete.CookLevin.BuilderSecondClauseSecondLiteralPrefix.specification_secondLiteral_unaryUnit_step',
    'PNP.Concrete.CookLevin.BuilderSecondClauseSecondLiteralPrefix.specification_secondLiteral_terminator_step',
    'PNP.Concrete.CookLevin.BuilderSecondClauseSecondLiteralPrefix.finalTokenBits_eq_encodedFormula_secondClauseSecondLiteral',
    'PNP.Concrete.CookLevin.BuilderSecondClauseSecondLiteralPrefix.finalTokenSlot_eq_secondClauseStart_add_six',
    'status.leanConcreteCookLevinBuilderSecondClauseSecondLiteralPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSecondLiteralPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSecondLiteralPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSecondLiteralPrefixCompleteSecondNegativeLiteralFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClauseSecondLiteralPrefixRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondClausePrefix.specification_terminator_step',
    'PNP.Concrete.CookLevin.BuilderSecondClausePrefix.finalTokenBits_eq_encodedFormula_secondClause',
    'PNP.Concrete.CookLevin.BuilderSecondClausePrefix.finalTokenSlot_eq_secondClauseStart_add_seven',
    'PNP.Concrete.CookLevin.BuilderSecondClausePrefix.nextTokenSlot_direct_eq_padding',
    'status.leanConcreteCookLevinBuilderSecondClausePrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondClausePrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePrefixCompleteSecondClauseFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePrefixClauseTerminatorFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePrefixRetainedFirstPaddingCoordinateFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePrefixRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondClausePaddingRun.specification_padding_run',
    'PNP.Concrete.CookLevin.BuilderSecondClausePaddingRun.finalTokenBits_eq_encodedFormula_secondClause',
    'PNP.Concrete.CookLevin.BuilderSecondClausePaddingRun.finalTokenSlot_eq_thirdClauseStart',
    'PNP.Concrete.CookLevin.BuilderSecondClausePaddingRun.thirdClauseStart_direct_eq_sep',
    'status.leanConcreteCookLevinBuilderSecondClausePaddingRunFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePaddingRunAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondClausePaddingRunExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePaddingRunRemainingPaddingCountFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePaddingRunDirectPaddingBlockFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePaddingRunThirdClauseStartFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondClausePaddingRunNoEmissionSpecificationFormalized === true',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSeparatorStep.specification_separator_step',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSeparatorStep.finalTokenBits_eq_encodedFormula_thirdClauseStart',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSeparatorStep.finalTokenSlot_eq_thirdClauseStart_add_one',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSeparatorStep.nextTokenSlot_direct_eq_f',
    'status.leanConcreteCookLevinBuilderThirdClauseSeparatorStepFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSeparatorStepAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSeparatorStepExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSeparatorStepThirdClauseSeparatorFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSeparatorStepRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderThirdClauseFirstLiteralPrefix.specification_firstLiteral_sign_step',
    'PNP.Concrete.CookLevin.BuilderThirdClauseFirstLiteralPrefix.specification_firstLiteral_terminator_step',
    'PNP.Concrete.CookLevin.BuilderThirdClauseFirstLiteralPrefix.finalTokenBits_eq_encodedFormula_thirdClauseFirstLiteral',
    'PNP.Concrete.CookLevin.BuilderThirdClauseFirstLiteralPrefix.finalTokenSlot_eq_thirdClauseStart_add_three',
    'PNP.Concrete.CookLevin.BuilderThirdClauseFirstLiteralPrefix.nextTokenSlot_direct_eq_f',
    'status.leanConcreteCookLevinBuilderThirdClauseFirstLiteralPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseFirstLiteralPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderThirdClauseFirstLiteralPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseFirstLiteralPrefixCompleteFirstNegativeLiteralFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseFirstLiteralPrefixRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSecondLiteralPrefix.specification_secondLiteral_sign_step',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSecondLiteralPrefix.specification_secondLiteral_unaryUnit_step',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSecondLiteralPrefix.specification_secondLiteral_secondUnaryUnit_step',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSecondLiteralPrefix.specification_secondLiteral_terminator_step',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSecondLiteralPrefix.finalTokenBits_eq_encodedFormula_thirdClauseSecondLiteral',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSecondLiteralPrefix.finalTokenSlot_eq_thirdClauseStart_add_seven',
    'PNP.Concrete.CookLevin.BuilderThirdClauseSecondLiteralPrefix.nextTokenSlot_direct_eq_finish',
    'status.leanConcreteCookLevinBuilderThirdClauseSecondLiteralPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSecondLiteralPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSecondLiteralPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSecondLiteralPrefixCompleteSecondNegativeLiteralFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClauseSecondLiteralPrefixRetainedClauseTerminatorCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderThirdClausePrefix.specification_terminator_step',
    'PNP.Concrete.CookLevin.BuilderThirdClausePrefix.finalTokenBits_eq_encodedFormula_thirdClause',
    'PNP.Concrete.CookLevin.BuilderThirdClausePrefix.finalTokenSlot_eq_thirdClauseStart_add_eight',
    'PNP.Concrete.CookLevin.BuilderThirdClausePrefix.nextTokenSlot_direct_eq_padding',
    'status.leanConcreteCookLevinBuilderThirdClausePrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderThirdClausePrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePrefixCompleteThirdClauseFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePrefixRetainedFirstPaddingCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderThirdClausePaddingRun.specification_padding_run',
    'PNP.Concrete.CookLevin.BuilderThirdClausePaddingRun.finalTokenBits_eq_encodedFormula_thirdClause',
    'PNP.Concrete.CookLevin.BuilderThirdClausePaddingRun.finalTokenSlot_eq_fourthClauseStart',
    'PNP.Concrete.CookLevin.BuilderThirdClausePaddingRun.fourthClauseStart_direct_eq_sep',
    'status.leanConcreteCookLevinBuilderThirdClausePaddingRunFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePaddingRunAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderThirdClausePaddingRunExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePaddingRunRemainingPaddingCountFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePaddingRunDirectPaddingBlockFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePaddingRunFourthClauseStartFormalized === true',
    'status.leanConcreteCookLevinBuilderThirdClausePaddingRunNoEmissionSpecificationFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSeparatorStep.specification_separator_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSeparatorStep.finalTokenBits_eq_encodedFormula_fourthClauseStart',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSeparatorStep.finalTokenSlot_eq_fourthClauseStart_add_one',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSeparatorStep.nextTokenSlot_direct_eq_f',
    'status.leanConcreteCookLevinBuilderFourthClauseSeparatorStepFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSeparatorStepAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSeparatorStepExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSeparatorStepFourthClauseSeparatorFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSeparatorStepRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFourthClauseFirstLiteralPrefix.specification_firstLiteral_sign_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseFirstLiteralPrefix.specification_firstLiteral_unaryUnit_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseFirstLiteralPrefix.specification_firstLiteral_terminator_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseFirstLiteralPrefix.finalTokenBits_eq_encodedFormula_fourthClauseFirstLiteral',
    'PNP.Concrete.CookLevin.BuilderFourthClauseFirstLiteralPrefix.finalTokenSlot_eq_fourthClauseStart_add_four',
    'PNP.Concrete.CookLevin.BuilderFourthClauseFirstLiteralPrefix.nextTokenSlot_direct_eq_f',
    'status.leanConcreteCookLevinBuilderFourthClauseFirstLiteralPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseFirstLiteralPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFourthClauseFirstLiteralPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseFirstLiteralPrefixCompleteFirstNegativeLiteralFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseFirstLiteralPrefixRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSecondLiteralPrefix.specification_secondLiteral_sign_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSecondLiteralPrefix.specification_secondLiteral_unaryUnit_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSecondLiteralPrefix.specification_secondLiteral_secondUnaryUnit_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSecondLiteralPrefix.specification_secondLiteral_terminator_step',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSecondLiteralPrefix.finalTokenBits_eq_encodedFormula_fourthClauseSecondLiteral',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSecondLiteralPrefix.finalTokenSlot_eq_fourthClauseStart_add_eight',
    'PNP.Concrete.CookLevin.BuilderFourthClauseSecondLiteralPrefix.nextTokenSlot_direct_eq_finish',
    'status.leanConcreteCookLevinBuilderFourthClauseSecondLiteralPrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSecondLiteralPrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSecondLiteralPrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSecondLiteralPrefixCompleteSecondNegativeLiteralFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClauseSecondLiteralPrefixRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFourthClausePrefix.specification_terminator_step',
    'PNP.Concrete.CookLevin.BuilderFourthClausePrefix.finalTokenBits_eq_encodedFormula_fourthClause',
    'PNP.Concrete.CookLevin.BuilderFourthClausePrefix.finalTokenSlot_eq_fourthClauseStart_add_nine',
    'PNP.Concrete.CookLevin.BuilderFourthClausePrefix.nextTokenSlot_direct_eq_padding',
    'status.leanConcreteCookLevinBuilderFourthClausePrefixFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClausePrefixAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFourthClausePrefixExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClausePrefixCompleteFourthClauseFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClausePrefixRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFourthClausePaddingRun.specification_padding_run',
    'PNP.Concrete.CookLevin.BuilderFourthClausePaddingRun.specification_target_step',
    'PNP.Concrete.CookLevin.BuilderFourthClausePaddingRun.finalTokenBits_eq_encodedFormula_fourthClause',
    'PNP.Concrete.CookLevin.BuilderFourthClausePaddingRun.finalTokenSlot_eq_fifthClauseSlotStart',
    'PNP.Concrete.CookLevin.BuilderFourthClausePaddingRun.paddingSlot_direct_eq_padding',
    'PNP.Concrete.CookLevin.BuilderFourthClausePaddingRun.fifthClauseSlotStart_direct_eq_padding',
    'status.leanConcreteCookLevinBuilderFourthClausePaddingRunFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClausePaddingRunAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFourthClausePaddingRunExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClausePaddingRunRemainingPaddingCountFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClausePaddingRunFifthClauseSlotStartFormalized === true',
    'status.leanConcreteCookLevinBuilderFourthClausePaddingRunNoEmissionSpecificationFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFifthClausePaddingRun.specification_padding_run',
    'PNP.Concrete.CookLevin.BuilderFifthClausePaddingRun.specification_target_step',
    'PNP.Concrete.CookLevin.BuilderFifthClausePaddingRun.finalTokenBits_eq_encodedFormula_fourthClause',
    'PNP.Concrete.CookLevin.BuilderFifthClausePaddingRun.finalTokenSlot_eq_sixthClauseSlotStart',
    'PNP.Concrete.CookLevin.BuilderFifthClausePaddingRun.paddingSlot_direct_eq_padding',
    'PNP.Concrete.CookLevin.BuilderFifthClausePaddingRun.sixthClauseSlotStart_direct_eq_padding',
    'status.leanConcreteCookLevinBuilderFifthClausePaddingRunFormalized === true',
    'status.leanConcreteCookLevinBuilderFifthClausePaddingRunAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFifthClausePaddingRunExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFifthClausePaddingRunPaddingCountFormalized === true',
    'status.leanConcreteCookLevinBuilderFifthClausePaddingRunSixthClauseSlotStartFormalized === true',
    'status.leanConcreteCookLevinBuilderFifthClausePaddingRunNoEmissionSpecificationFormalized === true',
    'PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.specification_padding_run',
    'PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.specification_target_step',
    'PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalTokenBits_eq_encodedFormula_fourthClause',
    'PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalTokenSlot_eq_secondConstraintStart',
    'PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingSlot_direct_eq_padding',
    'PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.secondConstraintStart_direct_eq_sep',
    'status.leanConcreteCookLevinBuilderFirstConstraintPaddingRunFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstConstraintPaddingRunAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderFirstConstraintPaddingRunExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstConstraintPaddingRunPaddingCountFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstConstraintPaddingRunSecondConstraintSeparatorFormalized === true',
    'status.leanConcreteCookLevinBuilderFirstConstraintPaddingRunNoEmissionSpecificationFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintSeparatorStep.specification_separator_step',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintSeparatorStep.specification_next_step',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintSeparatorStep.finalTokenBits_eq_encodedFormula_secondConstraintStart',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintSeparatorStep.finalTokenSlot_eq_secondConstraintStart_add_one',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintSeparatorStep.nextTokenSlot_direct_eq_t',
    'status.leanConcreteCookLevinBuilderSecondConstraintSeparatorStepFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintSeparatorStepAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintSeparatorStepExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintSeparatorStepSecondConstraintSeparatorFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintSeparatorStepRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralSignStep.specification_sign_step',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralSignStep.specification_next_step',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralSignStep.finalTokenBits_eq_encodedFormula_secondConstraintFirstLiteralSign',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralSignStep.finalTokenSlot_eq_secondConstraintStart_add_two',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralSignStep.nextTokenSlot_direct_eq_t',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralSignStepFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralSignStepAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralSignStepExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralSignStepSecondConstraintFirstLiteralSignFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralSignStepRetainedAdvancedTokenCoordinateFormalized === true',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralFirstUnaryUnitStep.specification_firstUnaryUnit_step',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralFirstUnaryUnitStep.specification_next_step',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralFirstUnaryUnitStep.finalTokenBits_eq_encodedFormula_secondConstraintFirstLiteralFirstUnary',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralFirstUnaryUnitStep.finalTokenSlot_eq_secondConstraintStart_add_three',
    'PNP.Concrete.CookLevin.BuilderSecondConstraintFirstLiteralFirstUnaryUnitStep.nextTokenSlot_direct_eq_t',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralFirstUnaryUnitStepFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralFirstUnaryUnitStepAxiomAuditPassed === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralFirstUnaryUnitStepExactFormulaBitsFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralFirstUnaryUnitStepSecondConstraintFirstLiteralFirstUnaryUnitFormalized === true',
    'status.leanConcreteCookLevinBuilderSecondConstraintFirstLiteralFirstUnaryUnitStepRetainedAdvancedTokenCoordinateFormalized === true',
    'status.leanConcreteCookLevinBuilderInputPrefixAppenderComposed === true',
    'status.leanConcreteCookLevinBuilderDynamicCursorFormalized === false',
    'status.leanConcreteCookLevinFormulaBuilderFormalized === false',
    'PNP.Concrete.TerminalOutputPacker.machineOutput_compileTerminalOutputPacker_eq',
    'status.leanConcretePipelineTerminalOutputPackingFormalized === true',
    'status.leanConcretePipelineTerminalOutputPackerAxiomAuditPassed === true',
    'status.leanConcretePipelineTerminalOutputPackerConnectedToBridgeEndpointFormalized === true',
    'status.leanConcretePipelineTerminalBridgeAxiomAuditPassed === true',
    'status.leanConcretePipelinePriorTraceTransportToTerminalBridgeFormalized === true',
    'PNP.Concrete.PipelineInputFramer.totalInputFramer_workRunExact',
    'PNP.Concrete.PipelineInputFramer.run_compileTotalInputFramer_encoded_rawTimeBound',
    'status.leanConcretePipelineInputFramerAxiomAuditPassed === true',
    'status.leanConcretePipelineAllInputFramingFormalized === true',
    'PNP.Concrete.PipelineTerminalBridge.outputBits_compileTerminalBridge_accepting_of_represents',
    'PNP.Concrete.PipelinePairedCompiler.pairedPipeline_boundedDecide_eq',
    'PNP.Concrete.PipelinePairedCompiler.pairedPipeline_machineOutput_eq',
    'PNP.Concrete.PipelinePairedCompiler.pairedPipeline_ne_timeout',
    'PNP.Concrete.PipelinePairedCompiler.pairedPipeline_accepts_iff',
    'status.leanConcretePipelinePairedCompilerAxiomAuditPassed === true',
    'status.leanConcretePipelineCanonicalPairCompilationFormalized === true',
    'PNP.Concrete.PipelineCompiler.pipeline_boundedDecide_eq',
    'PNP.Concrete.PipelineCompiler.pipeline_machineOutput_eq',
    'PNP.Concrete.PipelineCompiler.pipeline_ne_timeout',
    'PNP.Concrete.PipelineCompiler.pipeline_accepts_iff',
    'status.leanConcretePipelineCompilerAxiomAuditPassed === true',
    'status.leanConcretePipelineAllInputCompilationFormalized === true',
    'status.leanConcretePipelineMalformedInputBehaviorFormalized === true',
    'status.leanConcretePipelineRawRefinementFormalized === true',
    'status.leanConcretePipelineSequentialCompilerAxiomAuditPassed === true',
    'status.leanConcretePipelineRefinementAxiomAuditPassed === true',
    'status.leanConcreteFunctionProgramRecursiveCompilationFormalized === true',
    'status.leanConcretePipelineExternalInputSizePolynomialFormalized === true',
    'status.leanConcreteCNFSATInPFormalized === false',
    'status.leanConcreteCNFNPCompletenessFormalized === false',
    'PNP.Main.ConcretePEqualsNP',
    'PNP.Main.p_eq_np',
    'abstractPEqualsNPPublicationEligible === false',
    'publicationStatusDerivedOnlyFromConcreteGate === true',
    'const strictConjunction = GATE_SUBCHECK_KEYS.every',
    'typeConfigured && gate.actualConcreteTargetKernelTypeSha256',
    'sourceConfigured && gate.actualSourceClosureSha256',
    'status.mathematicalTheoremEstablished === gatePassed',
    'status.publicTheoremEmissionAllowed === gatePassed',
    'status.formalPublicationMilestones',
    "fetch('public/pnp-status.json'",
    "fetch('public/pnp-theorem-inventory.json'",
    'Promise.all([',
    'compiled Lean inventory digest mismatch',
    'renderMilestones(status.formalPublicationMilestones)',
    'loadFormalPublication();',
  ]) {
    assert.equal(script.includes(fragment), true, `missing formal-publication fragment: ${fragment}`);
  }
});

test('verify, FAQ, review, home, and status pages load the conservative shared script', async () => {
  for (const page of ['verify.html', 'faq.html', 'review.html', 'index.html', 'status.html']) {
    const html = await readText(page);
    assert.match(html, /<script src="assets\/main\.js" defer><\/script>/, `${page} must load assets/main.js`);
  }
});

test('status and inventory loading fails closed before either request validates', async () => {
  const script = await readText('assets/main.js');
  const initialFailClosed = script.indexOf("renderFormalStatus(root, FAIL_CLOSED_FORMAL_STATUS, 'fail-closed')");
  const fetchCall = script.indexOf("fetch('public/pnp-status.json'");
  assert.ok(initialFailClosed >= 0 && initialFailClosed < fetchCall, 'fail-closed state must render before fetch');
  assert.match(script, /if \(!statusResponse\.ok \|\| !inventoryResponse\.ok\) throw new Error/);
  assert.match(script, /if \(inventoryDigest !== INVENTORY_SHA256\) throw new Error/);
  assert.match(script, /if \(!isConservativeFormalStatus\(status, inventory\)\) throw new Error/);
  assert.match(script, /PNP formal-publication load failed closed/);
});
