import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';

async function readText(path) {
  return readFile(new URL(`../../${path}`, import.meta.url), 'utf8');
}

test('homepage leads with a plain, conservative result and the latest milestone', async () => {
  const html = await readText('index.html');
  for (const fragment of [
    'A machine-checked reconstruction of a proposed route to P = NP.',
    'Current result: P = NP is not established.',
    '<strong>P versus NP</strong> asks whether problems with answers that can be checked efficiently can also be solved efficiently.',
    '<strong>Lean</strong> is software that checks each stated mathematical step.',
    'Lean now publishes the concrete locked-NAND threshold reduction',
    'one uniform polynomial-time transformation from encoded CNF satisfiability instances',
    'PNP.Main.locked_nand_threshold',
    'ReducesTo CNFSAT EncodedLockedNANDThreshold',
    'compiled closure uses only <code>Quot.sound</code> and <code>propext</code>',
    'mathematicalTheoremEstablished = false',
    'publicTheoremEmissionAllowed = false',
    'rootLeanTheoremPresent = false',
    'projectSpecificAxiomsRemaining = true',
    'leanResidualTerminalFourCornerOptimumCoherenceClassifierFormalized = true',
    'leanResidualTerminalFourCornerOptimumFirstFailureFormalized = true',
    'leanResidualTerminalFourCornerOptimumRetainedSemanticsFormalized = true',
    'leanResidualTerminalFourCornerOptimumProfileTransportFormalized = true',
    'leanResidualTerminalFourCornerOptimumModeFirewallFormalized = true',
    'leanResidualTerminalFourCornerOptimumSideTightTupleFactsFormalized = true',
    'leanResidualTerminalFourCornerOptimumCoherenceAxiomAuditPassed = true',
    'leanResidualTerminalFourCornerOptimumLocalRouteClassifierFormalized = true',
    'leanResidualTerminalFourCornerOptimumRouteSoundnessFormalized = true',
    'leanResidualTerminalFourCornerOptimumRouteSilenceFormalized = true',
    'leanResidualTerminalFourCornerOptimumSideTightCompletionUnderRouteSilenceFormalized = true',
    'leanResidualTerminalFourCornerOptimumExactCompletionValuesFormalized = true',
    'leanResidualTerminalFourCornerOptimumPromotionFirewallRetained = true',
    'leanResidualTerminalFourCornerSideTightCompletionAxiomAuditPassed = true',
    'leanResidualTerminalFourCornerArbitraryFamilyCoherenceFormalized = true',
    'leanResidualTerminalFourCornerExactMinimumFamilyEnumerated = true',
    'leanResidualTerminalFourCornerTightBasisFamilyComplete = true',
    'leanResidualTerminalFourCornerSignedTightBasisMaximumFormalized = true',
    'leanResidualTerminalFourCornerTightBasisMaximumEqualsDeltaFormalized = true',
    'leanResidualTerminalFourCornerTightBasisMaximumAxiomAuditPassed = true',
    'leanLockedNANDCarrierLayoutFormalized = true',
    'leanLockedNANDGlobalCandidateAssemblyFormalized = true',
    'leanLockedNANDGlobalBaselineDistinctFormalized = true',
    'leanLockedNANDUnsatisfiableFinalZeroFormalized = true',
    'leanLockedNANDGlobalSemanticThresholdFormalized = true',
    'leanConcreteLockedNANDEncodedSemanticReductionFormalized = true',
    'leanConcreteLockedNANDParserMachineFormalized = true',
    'leanConcreteLockedNANDParserAxiomAuditPassed = true',
    'leanConcreteLockedNANDParserAuditedDeclarationCount = 380',
    'leanConcreteLockedNANDParserAllInputExactFormalized = true',
    'leanConcreteLockedNANDParserExactOutputFormalized = true',
    'leanConcreteLockedNANDParserCompiledNonTimeoutFormalized = true',
    'leanConcreteLockedNANDParserPolynomialTimeMachineFormalized = true',
    'leanConcreteLockedNANDParserPolynomialTimeFunctionFormalized = true',
    'leanConcreteLockedNANDParserRawRefinementFormalized = true',
    'leanConcreteLockedNANDEmitterMachineFormalized = true',
    'leanConcreteLockedNANDEmitterAxiomAuditPassed = true',
    'leanConcreteLockedNANDEmitterAuditedDeclarationCount = 3295',
    'leanConcreteLockedNANDEmitterAllInputExactFormalized = true',
    'leanConcreteLockedNANDEmitterExactTargetBytesFormalized = true',
    'leanConcreteLockedNANDEmitterCompiledNonTimeoutFormalized = true',
    'leanConcreteLockedNANDEmitterPolynomialTimeMachineFormalized = true',
    'leanConcreteLockedNANDEmitterPolynomialTimeFunctionFormalized = true',
    'leanConcreteLockedNANDEmitterRawRefinementFormalized = true',
    'leanConcreteLockedNANDEmitterStrictParserCompositionFormalized = true',
    'leanConcreteLockedNANDEmitterOutputSizeBoundFormalized = true',
    'leanConcreteLockedNANDPolynomialReductionFormalized = true',
    'leanConcreteCNFToNANDSemanticCompilerFormalized = true',
    'leanConcreteCNFToNANDSemanticCompilerAuditedDeclarationCount = 68',
    'leanConcreteCNFToNANDExactSemanticsFormalized = true',
    'leanConcreteCNFToNANDPolynomialOutputSizeBoundFormalized = true',
    'leanConcreteCNFToNANDFiniteMachineFormalized = true',
    'leanConcreteCNFToNANDPolynomialTimeFunctionFormalized = true',
    'leanConcreteCNFToNANDPolynomialReductionFormalized = true',
    'leanConcreteCNFToNANDPolynomialReductionAuditedDeclarationCount = 1316',
    'leanConcreteCNFToNANDAllInputExactFormalized = true',
    'leanConcreteCNFToNANDExactMachineOutputFormalized = true',
    'leanConcreteCNFToNANDCompiledNonTimeoutFormalized = true',
    'leanConcreteCNFToNANDRawRefinementFormalized = true',
    'leanConcreteCNFToNANDDirectReductionFormalized = true',
    'leanConcreteCNFToNANDLockedReductionCompositionFormalized = true',
    'leanResidualGainChainVerifierFormalized = true',
    'leanResidualGainChainAxiomAuditPassed = true',
    'leanResidualGainChainSemanticInvariantFormalized = true',
    'leanResidualGainChainSlackIterationBoundFormalized = true',
    'leanLockedNANDGainIterationsAtMostFourFormalized = true',
    'leanResidualGainChainPolynomialRuntimeFormalized = false',
    'leanResidualGainStoppingSpecificationFormalized = true',
    'leanResidualGainStoppingAxiomAuditPassed = true',
    'leanResidualGainZeroIffGlobalNoStrictGainFormalized = true',
    'leanResidualGainSemanticMinimumIffGlobalNoStrictGainFormalized = true',
    'leanResidualGainChainGlobalStoppingConsequenceFormalized = true',
    'leanResidualTerminalFullBridgeFormalized = true',
    'leanResidualTerminalFullBridgeAxiomAuditPassed = true',
    'leanResidualTerminalizationExactFormalized = true',
    'leanResidualTerminalFullMinimumSpecificationFormalized = true',
    'leanResidualTerminalMuBridgeFormalized = true',
    'leanResidualWholeSpanPositiveWitnessIffFormalized = true',
    'leanResidualWholeSpanStrictDescentFormalized = true',
    'leanResidualWholeSpanZeroAbsenceIffFormalized = true',
    'leanResidualTerminalQuotientCarrierFormalized = true',
    'leanResidualTerminalModeFirewallFormalized = true',
    'leanResidualProjectionMinimumAxiomAuditPassed = true',
    'leanResidualProjectionMinimumExecutableFullScanFormalized = true',
    'leanResidualProjectionMinimumExecutableQuotientScanFormalized = true',
    'leanResidualProjectionMinimumMonotonicityFormalized = true',
    'leanResidualProjectionDefectZeroIffCheckedLiftAtMinimumFormalized = true',
    'leanResidualProjectionTransferFormalized = true',
    'leanResidualProjectionTransferAxiomAuditPassed = true',
    'leanResidualProjectionTransferSignedDeltasFormalized = true',
    'leanResidualProjectionTransferIdentityFormalized = true',
    'leanResidualProjectionTransferConstantCutFormalized = true',
    'leanResidualTerminalProperSupportFormalized = true',
    'leanResidualTerminalProperSupportSearchCompleteFormalized = true',
    'leanResidualTerminalProperSupportExactLocalGainFormalized = true',
    'leanResidualTerminalProperSupportAxiomAuditPassed = true',
    'leanResidualTerminalSupportSquareClosureFormalized = true',
    'leanResidualTerminalSupportSquareMeetJoinExactFormalized = true',
    'leanResidualTerminalSupportSquarePhysicalCompatibilityFormalized = true',
    'leanResidualTerminalSupportSquareSemanticExtractionFormalized = true',
    'leanResidualTerminalSupportSquareClosureAxiomAuditPassed = true',
    'leanResidualTerminalSaturationFormalized = true',
    'leanResidualTerminalSaturationAxiomAuditPassed = true',
    'leanResidualTerminalPrimitiveUniverseFormalized = true',
    'leanResidualTerminalSaturationExtensiveFormalized = true',
    'leanResidualTerminalSaturationLeastFormalized = true',
    'leanResidualTerminalSaturationMonotoneFormalized = true',
    'leanResidualTerminalSaturationIdempotentFormalized = true',
    'leanResidualTerminalExecutableSaturationFormalized = true',
    'leanResidualTerminalPhysicalSupportCompletionFormalized = true',
    'leanResidualTerminalPhysicalBoundaryFormalized = true',
    'leanResidualTerminalPhysicalInterfaceFormalized = true',
    'leanResidualTerminalPhysicalCompatibilityFormalized = true',
    'leanResidualTerminalPhysicalSupportCompletionAxiomAuditPassed = true',
    'leanResidualTerminalPhysicalSupportCompletionAuditedDeclarationCount = 35',
    'leanResidualTerminalPhysicalSupportCompletionEmptyAxiomDeclarationCount = 8',
    'leanResidualTerminalPhysicalSupportCompletionPropextOnlyDeclarationCount = 24',
    'leanResidualTerminalPhysicalSupportCompletionPropextQuotSoundDeclarationCount = 3',
    'leanResidualTerminalSupportExtractionFormalized = true',
    'leanResidualTerminalSupportExtractionAxiomAuditPassed = true',
    'leanResidualTerminalSupportExtractionAuditedDeclarationCount = 34',
    'leanResidualTerminalSupportExtractionEmptyAxiomDeclarationCount = 3',
    'leanResidualTerminalSupportExtractionPropextOnlyDeclarationCount = 11',
    'leanResidualTerminalSupportExtractionPropextQuotSoundDeclarationCount = 20',
    'leanResidualTerminalOpenSemanticsFormalized = true',
    'leanResidualTerminalInducedRecoveryFormalized = true',
    'leanResidualTerminalSupportCompletionFormalized = true',
    'leanResidualTerminalGovernedSupportCompletionFormalized = true',
    'leanResidualTerminalGovernedProfilePartitionFormalized = true',
    'leanResidualTerminalGovernedSupportCompletionAxiomAuditPassed = true',
    'leanResidualTerminalFrontierPushoutFormalized = true',
    'leanResidualTerminalFrontierBoundaryGlueExactFormalized = true',
    'leanResidualTerminalFrontierInterfaceGlueExactFormalized = true',
    'leanResidualTerminalFrontierProfileGlueExactFormalized = true',
    'leanResidualTerminalFrontierInternalizationFormalized = true',
    'leanResidualTerminalFrontierPushoutAxiomAuditPassed = true',
    'leanResidualTerminalProjectionSquareFormalized = true',
    'leanResidualTerminalProjectionPhysicalInvariantFormalized = true',
    'leanResidualTerminalProjectionProfileExactFormalized = true',
    'leanResidualTerminalProjectionMeetJoinCommuteFormalized = true',
    'leanResidualTerminalProjectionPushoutCommuteFormalized = true',
    'leanResidualTerminalProjectionSquareAxiomAuditPassed = true',
    'leanResidualTerminalSideTightMinimumArithmeticFormalized = true',
    'leanResidualTerminalSideTightSignedSlackIdentityFormalized = true',
    'leanResidualTerminalSideTightFailClosedGateFormalized = true',
    'leanResidualTerminalSideTightCanonicalFullBasisFormalized = true',
    'leanResidualTerminalSideTightCanonicalQuotientBasisFormalized = true',
    'leanResidualTerminalSideTightMinimumAxiomAuditPassed = true',
    'leanResidualTerminalFourCornerOptimaCarrierCompatibleFormalized = true',
    'leanResidualTerminalFourCornerOptimaFaithfulAmbientizationFormalized = true',
    'leanResidualTerminalFourCornerOptimaReferenceMinimumPreservedFormalized = true',
    'leanResidualTerminalFourCornerOptimaLocalizedMinimaFormalized = true',
    'leanResidualTerminalFourCornerOptimaSharedObserverProjectionFormalized = true',
    'leanResidualTerminalFourCornerOptimaAxiomAuditPassed = true',
    'leanResidualTerminalSquareLegitimacyFormalized = true',
    'leanResidualTerminalSquareStructuralCompatibilityFormalized = true',
    'leanResidualTerminalSquareFrontierPushoutFormalized = true',
    'leanResidualTerminalSquareSharedQuantityCarrierFormalized = true',
    'leanResidualTerminalSquareLocalConclusionUnderRouteSilenceFormalized = true',
    'leanResidualTerminalSquareFailClosedRouteDichotomyFormalized = true',
    'leanResidualTerminalSquareLegitimacyAxiomAuditPassed = true',
    'leanResidualTerminalComputedBCELAnchorNucleusFormalized = true',
    'leanResidualTerminalBCELMinimumPositiveNucleusFormalized = true',
    'leanResidualTerminalBCELAnchorAlgebraFormalized = true',
    'leanResidualTerminalBCELCutDefectFirewallFormalized = true',
    'leanResidualTerminalBCELCutRouteDichotomyFormalized = true',
    'leanResidualTerminalBCELConstantCutConclusionFormalized = true',
    'leanResidualTerminalBCELAnchorNucleusAxiomAuditPassed = true',
    'leanResidualTerminalSaturationPositivityFirewallFormalized = true',
    'leanResidualTerminalSaturationPositivityFirewallAxiomAuditPassed = true',
    'leanResidualTerminalCandidateSaturationFormalized = true',
    'leanResidualTerminalSaturationCostBalanceFormalized = true',
    'leanResidualTerminalFirstNontransparentStepFormalized = true',
    'leanResidualTerminalSaturationCostBalanceAxiomAuditPassed = true',
    'leanResidualTerminalInterfaceExposureRoutingFormalized = true',
    'leanResidualTerminalFiniteInterfaceExposureRoutesToEFormalized = true',
    'leanResidualTerminalInterfaceExposureZeroCostRetractFormalized = true',
    'leanResidualTerminalFirstInterfaceExposureRouteFormalized = true',
    'leanResidualTerminalInterfaceExposureRoutingAxiomAuditPassed = true',
    'leanResidualTerminalOriginKernelObligationRoutingFormalized = true',
    'leanResidualTerminalFiniteOriginKernelObligationClosureRoutedFormalized = true',
    'leanResidualTerminalFirstOriginKernelObligationRouteFormalized = true',
    'leanResidualTerminalOriginKernelObligationRoutingAxiomAuditPassed = true',
    'leanResidualTerminalFiniteSaturatePositiveCompositionFormalized = true',
    'leanResidualTerminalFiniteSaturatePositiveCompositionAxiomAuditPassed = true',
    'leanResidualTerminalRankWFFormalized = true',
    'leanResidualTerminalRankWFAxiomAuditPassed = true',
    'leanResidualTerminalRankWFScope = "fixed-ten-coordinate-natural-lexicographic-order-executable-comparison-accessibility-induction-and-kernel-well-foundedness"',
    'leanSaturatePositiveFormalized = false',
    'leanBCELReadyFormalized = false',
    'leanPCCMinPolynomialRuntimeFormalized = false',
    'concretePublicationGate.passed = false',
    'PNP-LEAN-THEOREM-INVENTORY-2026-08-10-122',
    'Lean now publishes the concrete locked-NAND threshold reduction',
    'updates.html#2026-08-10-concrete-locked-nand-threshold-publication',
    'Technical theorem boundary · gate closed · 5 blockers',
    'PNP.Main.locked_nand_threshold',
    'ReducesTo CNFSAT EncodedLockedNANDThreshold',
    'The 84% figure is a revisable estimate of known reconstruction work',
    'About 84% of the known formalisation work',
    'not a probability that the claim is correct, a confidence score, or a mathematical result',
    'P: problems we can solve efficiently',
    'NP: answers we can check efficiently',
    'Read the plain-language and technical update',
    'Machine checking now connects CNF-SAT through exact polynomial reductions, not to an efficient solver.',
    'EncodedLockedNANDThreshold',
  ]) assert.equal(html.includes(fragment), true, `missing homepage fragment: ${fragment}`);
  const latestMilestone = html.match(/<article class="latest-milestone"[\s\S]*?<\/article>/u)?.[0] ?? '';
  assert.doesNotMatch(latestMilestone, /residual terminal rank|83%|6 blockers/iu);
  assert.doesNotMatch(html, />Historical report</u);
});

test('homepage technical boundary and release identifiers are visibly discoverable but collapsed by default', async () => {
  const html = await readText('index.html');
  assert.match(html, /<details class="boundary-panel" data-formal-status-root data-status-state="fail-closed">/u);
  assert.match(html, /Show technical boundary/u);
  assert.match(html, /Hide technical boundary/u);
  assert.match(html, /class="disclosure-chevron"/u);
  assert.match(html, /<details class="release-details">/u);
  assert.match(html, /Source and release identifiers/u);
  assert.doesNotMatch(html, /<details class="(?:boundary-panel|release-details)"[^>]*\sopen(?:\s|=|>)/u);
  assert.match(html, /data-formal-status-fields[\s\S]*data-formal-status-note[\s\S]*<\/details>/u);
});

test('homepage content is authoritative without JavaScript copy rewriting', async () => {
  const script = await readText('assets/main.js');
  for (const forbidden of [
    'ensureHomepageFormalReconstructionBoundary',
    'rewritePageHero',
    'insertAfterPageHero',
    'ensureStatusLink',
    'data-homepage-matrix-summary',
    'data-homepage-one-command-upload',
  ]) assert.doesNotMatch(script, new RegExp(forbidden, 'u'), forbidden);
  assert.match(script, /async function loadFormalPublication\(\)/u);
  assert.match(script, /loadFormalPublication\(\);/u);
});
